name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * 0'  # Weekly: Sunday 03:00 UTC
  workflow_dispatch:      # Manual trigger (on demand)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history required for sync

      - name: Sync upstream to fork
        uses: repo-sync/github-sync@v3
        with:
          source_repo: 'ethereum/execution-spec-tests'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sync_tags: false
          pull_request: true
          pull_request_title: 'Sync fork with EST upstream'
          pull_request_body: 'Updates the fork with the latest changes from EST upstream.'
          pull_request_branch_name: 'sync-upstream-${{ github.run_number }}'