name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * 0'  # Weekly: Sunday 03:00 UTC
  workflow_dispatch:      # Manual trigger (optional)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history required for merge

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ethereum/execution-spec-tests.git
          git fetch upstream main

      - name: Merge upstream changes
        run: |
          git checkout main
          git rebase upstream/main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN is sufficient here
          commit-message: "Sync fork with upstream"
          title: "Sync fork with upstream"
          body: "This PR updates the fork with the latest changes from upstream."
          branch: sync-upstream-${{ github.run_number }}
          base: main